image: alpine/edge
secrets:
  - 7fe491a0-a779-4a4a-baed-7db227ac60d3
  - 76f26286-d95d-421d-97ad-ad33ca880e4d
environment:
  deploy: webmin@www.ekho.digital
packages:
  - hugo
sources:
  - https://git.sr.ht/~ekho/ekho-digital
triggers:
  - action: email
    condition: always
    to: notif+builds@ekho.email
tasks:
  - build: |
      cd ekho-digital
      hugo
  - deploy: |
      cd ekho-digital
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then complete-build; fi
      ssh -p 50022 ${deploy}
